chrome/script.js, firefox/script.js, shared.js
this partially addresses [issue#16](https://github.com/kheina-com/Blue-Blocker/issues/16) by having the in-memory block queue sync to the local storage. this also allows the queue to be shared by tabs with a low risk of conflict
=> store block queue in local storage

shared.js
fixes a bug in the `skip1Mplus` option where accounts with zero followers were accidentally skipped as well. This PR fixes https://github.com/kheina-com/Blue-Blocker/issues/24
=> Fix Zero Followers Bug in skip1Mplus Option

makefile
updates makefile for packing the zips correctly since there is no more firefox or chrome folders anymore
=> update makefile for no split platform folders

firefox-manifest.json, manifest.json
realized I still had the active tab requirement in the manifests even though I removed the code that used it. this does not bump the version
=> remove active tab requirement from manifests

firefox-manifest.json, popup.html, service_worker.js, shared.js
this PR addresses https://github.com/kheina-com/Blue-Blocker/issues/39
as described in the issue, firefox ESR releases do not support manifest V3 yet, so to maintain full support, revert firefox manifest version back to 2
=> Reset Firefox Manifest to Version 2

injected/inject.js, parsers/instructions.js, script.js
Resolves #118
Looks like they added/changed the name of the search endpoint. First time looking through all of this, so even that I'm not sure of - all I know is that this fixes the problem.
It looks like there could be different search types, but I'm not sure how to adapt the current instructions key array format to fit that, so this just works for the most basic use case: searching by typing text in the box. It appears to still work fine for hashtags and cashtags and advanced search, and I can't even find another search type besides `search_by_raw_query`, so I think this is sufficient for now.
=> Add instructions and matching for the SearchTimeline endpoint.

makefile, src/manifest.ts, src/popup/index.html, src/popup/index.ts, src/popup/style.css
addresses #141, also addresses #155
the quickmenu only has 5 or 6 options in it and does not scroll. advanced menu has everything in it and will be where new options are added from now on.
to add a new checkbox option, follow the existing format in the html:
```html
<div class="option">
<label for="skip-verified" name="skip-verified">
<div class="checkmark">
<div></div>
</div>
<p>skip legacy verified users</p>
</label>
<span name="skip-verified-status"></span>
</div>
```
status can be omitted on the quick page
and then registered on the backend like this:
```typescript
// custom callback
checkHandler(suspendBlockCollection, config, "suspendedBlockCollection", {
callback(target) {
// notice you need to update status yourself
document.getElementsByName(target.id + "-status").forEach(status …
```
=> add quick and advanced tabs to the popup menu

CHANGELOG.md, package.json, src/background/db.ts, src/background/index.ts, src/constants.ts, src/content/index.ts, src/content/startup.ts, src/global.d.ts, src/injected/inject.ts, src/injected/style.css, src/manifest.ts, src/models/block_queue.ts, src/models/queue_consumer.ts, src/pages/history/index.html, src/pages/history/index.ts, src/pages/history/style.css, src/pages/queue/index.html, src/pages/queue/index.ts, src/pages/queue/style.css, src/pages/safelist/index.html, src/pages/safelist/index.ts, src/pages/safelist/style.css, src/parsers/unblock.ts, src/popup/index.html, src/popup/index.ts, src/popup/style.css, src/shared.ts, src/utilities.ts, vite.config.ts
This is a long-lived branch, intended to aggregate all changes planned for version `VERSION`.
Pull requests should be made against this branch. Features should be added to this branch via a **squash** commit. When ready, this branch should be merged to main via a **merge** commit.
- feat: track block history, click blocked number in context menu to access (#63)
- feat: added safelist control buttons: import, export, clear
- feat: import block lists into queue via json files (#145)
- feat: added close button to all popups (#68)
- feat: auto-safelist unblocked users (#136)
- update: popups can now be placed in any corner of the screen (#68)
- fix: skip legacy verified error recovery
- chore: make toasts slightly slimmer
- chore: more and better header assignment
- chore: add entropy to …
=> Block History, Safelist Importing, Blocklist Importing, Popup Options, etc

package-lock.json, package.json, src/global.d.ts, src/manifest.ts, src/shared.ts
This is a short-lived feature fix branch, once it is ready to go it should squashed and merged into main.
- 0.3.6 
- Fix: Check to see if an account is already muted if the mute option is active
- Fix #198 
- Fix: Change the definition of the `BlueBlockUser` interface to reflect the optionality of `user.legacy.blocking`
- Chore: Run prettier on global.d.ts and shared.ts
- 0.3.7
-  Update: Use mute option while generating console messages and toasts
1. [x] ensure `src/manifest.ts` and `package.json` have the correct version number
2. [ ] use makefile to generate zips (`make chrome`, `make firefox`)
3. [ ] merge branch into main
4. [ ] upload zips from `3` to chrome webstore and firefox addons
=> Mute check fix

package-lock.json, package.json, src/constants.ts, src/global.d.ts, src/manifest.ts, src/parsers/search.ts, src/parsers/timeline.ts, src/popup/index.html, src/popup/index.ts, src/shared.ts
See #228 for reasoning.
- Remove blockNftAvatars property from config and checks
- Remove option from popup
1. [x] ensure `src/manifest.ts` and `package.json` have the correct version number
2. [ ] use makefile to generate zips (`make chrome`, `make firefox`)
3. [ ] merge into main
4. [ ] upload zips from `3` to chrome webstore and firefox addons
=> Nft removal

package-lock.json, package.json, src/content/index.ts, src/manifest.ts, src/shared.ts
This PR adds support for OldTwitter, and resolves #185
Support for this was added in https://github.com/dimdenGD/OldTwitter/pull/703 (auth fix in https://github.com/dimdenGD/OldTwitter/pull/704)
- Added an event listener to shared.ts that listens for `OLDTWITTER_REQUEST_LOAD` requests
- This then emits `blue-blocker-event`s containing the OldTwitter request information
1. [ ] merge all pull requests to llb
2. [ ] ensure `src/manifest.ts` and `package.json` have the correct version number
3. [x] use makefile to generate zips (`make chrome`, `make firefox`)
4. [ ] merge llb to main
=> feat: add OldTwitter support

package-lock.json, package.json, src/manifest.ts, src/parsers/search.ts
No idea what semver string to use here! 
- [FIX] Error involving typeahead in DM composer, close #189 
2. [ ] ensure `src/manifest.ts` and `package.json` have the correct version number
3. [ ] use makefile to generate zips (`make chrome`, `make firefox`)
4. [ ] merge llb to main
=> Fix typeahead error in DM composer

.github/workflows/release.yml, makefile
Blue Blocker has obtained a life outside of my own efforts. To that end, I did what I could to add a new github workflow that would allow others to just create a github release and the workflow _should_ just build and upload everything automatically
I haven't tested this yet because I'm honestly not sure how you would go about doing that without making a new release. But, I've created the necessary tokens and they are already in the repo secrets so everything should be there to make it work.
here are the actions I used in case anyone wants to double check my work:
https://github.com/marketplace/actions/publish-firefox-add-on
https://github.com/marketplace/actions/chrome-extension-upload-publish
- adds a github workflow to allow publishing new addon versions directly to chrome and firefox …
=> Add Release Workflow

.github/workflows/release.yml
adds an `npm run build` step prior to the make make steps in the release workflow
=> Add npm step to release workflow

.github/workflows/release.yml
using fully qualified version numbers in case the single numbers use `x.0.0` rather than the latest minor version. not sure why else there would have been unexpected input warnings
=> bump versions for everything to hopefully fix things

package-lock.json, package.json
Just run `npm version`, it's that easy! A 144444.99 dollar value that you get for the low low price of me losing my mind looking at npm man pages
- Add a version script that gets run when `npm version` runs
- That shit looks so ugly, i'm sooooo sorry. I didn't want to add a new file just for a goofy code chore
- Add config to package.json
- I set it so it won't make commits with the message "v<SemVer string>", that would be really annoying! It's also set so that we don't have a spam of tags that get fucky after squash and merges
=> Automate bumping manifest version

package-lock.json, package.json, src/manifest.ts, src/shared.ts
I did an oopsie whoopsie and flipped the logic in my brain!! It should now load the legacy database if config.blockForUse is true and user.used_blue is false, instead of if both are true
Note: this PR will merge into the 0.4.2 LLB, see #267 for the aggregating PR
=> [fix] change condition for checking legacy if user used blue

.github/workflows/release.yml
Should let approval notes, license and release notes paramaters to be submitted
=> [chore/fix] bump firefox-addon version

src/constants.ts
See title. We literally never use it, but it causes an incompatibility warning with Firefox.
Note: this is a PR against the 0.4.2 LLB. See #267 for the PR that aggregates changes to be applied to main.
=> [fix] remove reference to chrome.runtime.restartAfterDelay

src/background/index.ts, src/global.d.ts, src/shared.ts
Add an external integration endpoint that lets other extensions to start the integration setup process automatically. Users will still need to manually approve integrations, but won't need to find the extension ID anymore.
Note: this PR is against the 0.4.2 LLB, see #267 for the aggregating PR
=> [feat] integration registration prompt

package-lock.json, package.json, src/constants.ts, src/global.d.ts, src/popup/index.html, src/popup/index.ts, src/popup/style.css, src/shared.ts
closes #114
Allows blue blocker users to specifically block Twitter users with their own list of words/emojis. 
This is intended to block users with inflammatory or offensive names, but can also be used to block users who you might not vibe with, simply by defining a few keywords or emojis that can be seen on usernames of people you don't want to see on your timeline or replies.
For example, if you don't want to see users with the glitched 🏳️‍🌈” ⃠, emojis, or if you don't want to see🔞due to it being associated with NSFW accounts which is something you don't want to interact with. Just add it to the list in the extension's settings.
- I was unable to test on firefox due to it not being able to load the manifest file for some reason.
- the safelist buttons disappeared and I have no idea how …
=> [Feat] Add the ability to block users based on words/emojis in their username or display name

src/injected/inject.ts, src/manifest.ts, src/shared.ts
we should also take a serious look at these codeblocks, of which there are two in shared.ts
https://github.com/kheina-com/Blue-Blocker/blob/b4376ea4e1a6be81935c6b75ef65ba462d0ef854/src/shared.ts#L80-L84
https://github.com/kheina-com/Blue-Blocker/blob/b4376ea4e1a6be81935c6b75ef65ba462d0ef854/src/shared.ts#L80-L84
anything that references their domain name may have been updated including their api endpoints
Closes #280
=> Fix twitter x rename

package-lock.json, package.json, src/content/index.ts, src/injected/inject.ts, src/manifest.ts, src/parsers/instructions.ts
Pretty small and simple. To see the feature in action go to a page like 
[the likes on an Elon tweet](https://x.com/elonmusk/status/1793467069922725951/likes) and watch your queue go up!
1. [x] ensure `src/manifest.ts` and `package.json` have the correct version number
2. [ ] use makefile to generate zips (`make chrome`, `make firefox`)
=> [Feat] get users from tweet like pages

.github/CODEOWNERS
This should help keep review requests be more precisely targeted to relevant reviewers.
I made the decisions for who to assign to which files based on git history and blame, as well as in my personal case, just selecting files I'd be comfortable editing. Note that I didn't dig in too deep to the history in `src/*`, so it's possible there could be additional changes to make there. Also, I had previously added more names than this, but removed people who never responded to my invitations to collaborate on my fork.
=> Create a more granular version of CODEOWNERS

package-lock.json, package.json, src/manifest.ts, src/utilities.ts
Mozilla kinda had a point, we set the href attribute of an anchor tag to the escaped string. Therefore, we need to make sure to escape single and double quotes.
Definitely could be minimized slightly, but I want to make sure the reviewer understands what's happening fully. This is safe, it destroys tags, and does not allow you to escape the confines of an attribute in order to add tag level event handlers.
See #294 for more details.
1. [x] ensure `src/manifest.ts` and `package.json` have the correct version number
2. [x] use makefile to generate zips (`make chrome`, `make firefox`)
3. [ ] merge to main
=> Rewrite EscapeHTML func to be safer

makefile, package-lock.json, package.json, yarn.lock
jq package is a jQuery wrapper, and we don't use commander at all. 
node-jq allows us to use jq inside of node files, and as a side benefit it downloads the jq binary to `./node_modules/node-jq/bin/jq`. So we could update the makefile to use that binary, or alternatively turn the functionality of the makefile into a node script?
=> Use the correct jq package

.github/workflows/ci-main.yml, .github/workflows/release.yml, package-lock.json, package.json, readme.md, src/manifest.ts, yarn.lock
Bumps the version of @crxjs/vite-plugin that is used because it includes a fix for Chrome not recognizing dynamic URLs, see: https://github.com/crxjs/chrome-extension-tools/pull/928. Closes #365. Don't love that it means using a pre-release version of the package, but it is what it is... Hardcoded the specific version just in case a new beta drops.
I also specified a specific version of rollup in the package so that npm doesn't install a vulnerable version of it automatically... See: https://github.com/advisories/GHSA-gcx4-mw62-g8wm
Tested. Building works, and the extension no longer gets hit with a CSP error.
=> [fix] Dynamic URL fix

package-lock.json, package.json, src/constants.ts, src/content/index.ts, src/global.d.ts, src/manifest.ts, src/parsers/instructions.ts, src/popup/index.html, src/popup/index.ts
Pretty simple little feature to add. Closes #71.
Not super sure about what tab to put the option into, I think general is the best fit?
It should also probably be noted that for retweets, if you click on the tweet you get the page for the retweeted tweet directly which means you don't get information about who retweeted the status anymore. In other words, clicking on a tweet will make the check for retweeting by someone you follow to break and the tweet author will be blocked. 
Not super sure how to fix that issue though. One option is to add the retweeted user to the safelist, but I think that would override user intent in using the safelist.
=> [feat] Skip people retweeted by people you follow

package-lock.json, package.json, src/background/index.ts, src/manifest.ts, src/pages/consent/index.html
This should fix #383, and also includes some little changes that should make the flow work better for users on Firefox based browsers that are not Firefox. I also added some wording to the consent page about the popup possibly appearing again
=> Fix a bug where Firefox users were not getting the consent flow if they updated from non-listed versions
