- chrome/options.js
- chrome/popup.html
- chrome/script.js
- firefox-manifest.json
- firefox/options.js
- firefox/popup.html
- firefox/script.js
- manifest.json
- shared.js
- style.css
tested on both firefox and chrome.
this pull request partially addresses https://github.com/kheina-com/Blue-Blocker/issues/25
added local storage block counter. block counter is displayed in the popup menu (options menu)
> add block counter to popup menu

- chrome/options.js
- chrome/popup.html
- chrome/script.js
- firefox-manifest.json
- firefox/options.js
- firefox/popup.html
- firefox/script.js
- manifest.json
- shared.js
- style.css
This is a long-lived branch, intended to aggregate all changes planned for version 0.2.1.
Pull requests should be made against this branch
> v0.2.1 Long-Lived Branch

- options.js
- popup.html
- script.js
- shared.js
this PR fully addresses https://github.com/kheina-com/Blue-Blocker/issues/29
> Add option to mute

- options.js
- style.css
fix popup menu font size, move chrome only style to shared css file
> Fix chrome style and move to shared css

- .gitignore
- makefile
- options.js
- popup.html
- script.js
- shared.js
- style.css
increases the default block interval from 5 to 10 seconds and adds the ability to change the block interval from the context menu
this PR addresses https://github.com/kheina-com/Blue-Blocker/issues/18 and https://github.com/kheina-com/Blue-Blocker/issues/16
> Add Block Interval Config and Slider

- script.js
- shared.js
This PR addresses https://github.com/kheina-com/Blue-Blocker/issues/47
> Stop queue processing on logout

- .gitignore
- firefox-manifest.json
- makefile
- manifest.json
- options.js
- popup.html
- script.js
- service_worker.js
- shared.js
- style.css
This is a long-lived branch, intended to aggregate all changes planned for version `0.2.3`.
Pull requests should be made against this branch
- Revert FireFox manifest to v2 for ESR branches
- Set default block interval to 10 seconds
- Make block interval configurable from the context menu
- Set CSRF token directly from cookie (fixes many 403 errors)
- Stop processing block queue when user is logged out
1. [x] merge all pull requests to llb
2. [x] ensure manifests have the correct version/platform info (`manifest.json` points to chrome, `firefox-manifest.json` points to firefox)
3. [x] use makefile to generate zips (`make chrome`, `make firefox`)
4. [x] merge llb to main
fixes: …
> v0.2.3 Long-Lived Branch

- options.js
- popup.html
- style.css
> Show Version in Context Menu

- constants.js
- firefox-manifest.json
- inject.js
- main.js
- makefile
- manifest.json
- models/block_counter.js
- models/block_queue.js
- models/queue_consumer.js
- options.js
- parsers/instructions.js
- parsers/search.js
- parsers/timeline.js
- readme.md
- script.js
- service_worker.js
- shared.js
- utilities.js
- Restructure repository into separate parsers and models folders, shared.js is much cleaner
- Add multi-tab support. Only one queue will run at a time regardless of the number of twitter tabs open
- Adds support for search results pages and search bar suggestions
- Queue now purges duplicate users
this PR addresses https://github.com/kheina-com/Blue-Blocker/issues/44, https://github.com/kheina-com/Blue-Blocker/issues/49 (bonus: it also blocks people in the autofill bit of the search bar, too), https://github.com/kheina-com/Blue-Blocker/issues/32 (somewhat accidentally)
> Multi-Tab, Restructure, Search Pages

- shared.js
Closes #84 
Tested by adding to chrome and watching it block accounts
Also used this CodePen that shows how it handles a lot of missing data on user object: https://codepen.io/jaredkotoff/pen/MWPXYMP
Suggestions: 
* adding packjson.json and using jest for testing
* Typescript would also help avoid a lot of issues like this
* This could be helpful: https://github.com/guocaoyi/create-chrome-ext
> Check for undefined values in BlueBlueVerified

- constants.js
- firefox-manifest.json
- injected/inject.js
- shared.js
- utilities.js
I did it
also started using fetch instead of ajax since they didn't use proper formdata requests anyway
fixes: https://github.com/kheina-com/Blue-Blocker/issues/72, https://github.com/kheina-com/Blue-Blocker/issues/98
> Tweetdeck Support

- makefile
- readme.md
- src/constants.ts
- src/shared.ts
Fixes https://github.com/kheina-com/Blue-Blocker/issues/115
This PR increases the surface area of catching paid checkmarks by checking if the user is any of the "blockable" types and not depending on also having `is_blue_verified` flag set to true.
The initial assumption was the at gold check marks also had the `is_blue_verified` flag set to true, but it appears that not all gold/business checkmarks have this flag. 
See this comment for context and example of accounts that are not blocked at the moment: https://github.com/kheina-com/Blue-Blocker/issues/5#issuecomment-1569322041
example:
```json
{
"result": {
"__typename": "Tweet",
"rest_id": "1642318156784979969",
"core": {
"user_results": {
"result": {
"__typename": "User",
"id": "VXNlcjo4NzA2ODA5ODk=",
"rest_id": "870680989", …
```
> Fix the check for gold check marks

- firefox-manifest.json
- manifest.json
This is a long-lived branch, intended to aggregate all changes planned for version `0.3.0`.
Pull requests should be made against this branch
- fixes a bug in search results pages
1. [x] merge all pull requests to llb
2. [x] ensure manifests have the correct version/platform info (`manifest.json` points to chrome, `firefox-manifest.json` points to firefox)
3. [x] use makefile to generate zips (`make chrome`, `make firefox`)
4. [x] merge llb to main
> v0.2.7 Long-Lived Branch

- .github/pull_request_template.md
- makefile
- package-lock.json
- package.json
I still don't know how to delete a file if it exists
> Fix makefile, add pr template

- package-lock.json
- package.json
- src/background/index.ts
- src/content/index.ts
- src/manifest.ts
- src/popup/index.ts
- src/popup/style.css
- src/shared.ts
- src/utilities.ts
fix chrome109 issue in worker, add timeout to legacy db query, add more logs to idb.open, remove bots from affiliated blocks, fix quickmenu horizontal scrollbar, misc code clean
addresses: https://github.com/kheina-com/Blue-Blocker/issues/156 https://github.com/kheina-com/Blue-Blocker/issues/157 https://github.com/kheina-com/Blue-Blocker/issues/159
> Chrome109 fix, Legacy DB Patch, IDB.open Logs, Kkip Autoblocking Bots, cleanup

- src/content/index.ts
- src/global.d.ts
- src/injected/inject.ts
- src/injected/style.css
- src/pages/queue/index.ts
- src/pages/safelist/index.html
- src/pages/safelist/index.ts
- src/pages/safelist/style.css
- src/parsers/unblock.ts
- src/popup/index.html
- src/popup/index.ts
- src/popup/style.css
- src/shared.ts
- src/utilities.ts
- vite.config.ts
TODO: set history state to unblocked when getting unblock request
- feat: added safelist control buttons: import, export, clear
- feat: added close button to all popups
- feat: auto-safelist unblocked users
- chore: make toasts slightly slimmer
> safelist import and export

- src/models/block_queue.ts
- src/pages/queue/index.html
- src/pages/queue/index.ts
- src/pages/queue/style.css
block list importing
- feat: import json files into block list
> add import feature to queue

- src/constants.ts
- src/content/index.ts
- src/content/startup.ts
- src/global.d.ts
- src/injected/style.css
- src/popup/index.html
- src/popup/index.ts
- src/popup/style.css
- src/shared.ts
allows the users to set toasts in any corner of the screen
patch: popups can be placed in any corner of the screen
> toast location

- src/pages/history/index.html
- src/pages/history/index.ts
- src/pages/queue/index.html
- src/utilities.ts
no changelog for this PR, since everything is already included in llb
fixes:
- update history page logic so that reset button is shown even with 0 history
- update wording on queue import: say currently only json
- change history page title
> V0.3.3 quickfixes

- CHANGELOG.md
- package.json
- src/background/db.ts
- src/background/index.ts
- src/constants.ts
- src/content/startup.ts
- src/global.d.ts
- src/injected/style.css
- src/manifest.ts
- src/pages/history/index.ts
- src/pages/history/style.css
- src/pages/queue/index.html
- src/pages/queue/index.ts
- src/popup/index.html
- src/popup/index.ts
- src/popup/style.css
- src/shared.ts
- src/utilities.ts
fast follow for v0.3.3
- feat: show alert when user is logged out
- patch: write to history when block fails due to account deletion
- fix: retry after db failure
- fix: errors not surfacing during db transactions
- chore: add typedefs to all messages
- chore: display variance in popup
> Fix db transaction errors

- src/parsers/instructions.ts
This is a long-lived branch, intended to aggregate all changes planned for version `VERSION`.
Pull requests should be made against this branch. Merges to this branch should be done via a merge commit. When ready, this branch should be merged to main via a squash commit.
* Double check that the quoted/retweeted result object exists. Should fix #206.
```txt
Summary
1. document grouping follow 'SemVer2.0' protocol
2. use 'PATCH' as a minimum granularity
3. use concise descriptions
4. type: feat \ fix \ update \ perf \ remove \ docs \ chore
5. version timestamp follow the yyyy.MM.dd format
```
1. [ ] merge all pull requests to llb
2. [ ] ensure `src/manifest.ts` and `package.json` have the correct version number
3. [ ] use makefile to generate zips (`make chrome`, `make firefox`)
4. [ ] merge …
> Optionally chain result

- .github/CODEOWNERS
added codeowners so I can be more hands-off
> Add Codeowners File for Pull Requests

- .github/CODEOWNERS
This will give us one extra reviewer, which should help move PRs along a bit
> Add @rougetimelord to CODEOWNERS

- .github/workflows/release.yml
adds two more steps to the release workflow for setting up node and running npm install to install build dependencies
> add steps for node setup and build dependencies

- .github/workflows/release.yml
replacing old action with new one cuz the old one had fewer maintainers and annoyed me
> fuck it new chrome action

- .github/workflows/release.yml
> reword release notes because it should work now I think

- readme.md
Add info to how to build local firefox extension
> Update readme to include running build task

- package-lock.json
- package.json
- src/constants.ts
- src/global.d.ts
- src/manifest.ts
- src/parsers/instructions.ts
- src/popup/index.html
- src/popup/index.ts
- src/shared.ts
- [FEAT] Check tweet results for signs of previous editing, addresses some of #195 
- [FEAT] Add option to block legacy verified users if they use blue features, close #194 
2. [x] ensure `src/manifest.ts` and `package.json` have the correct version number
3. [ ] use makefile to generate zips (`make chrome`, `make firefox`)
4. [ ] merge llb to main
> Add check for tweets that have been edited

- src/global.d.ts
With the new integrations system I want to document everything that gets sent over so other extension devs can implement their own checks that use data that we don't.
Note: this PR will merge into the 0.4.2 LLB, see #267 for the aggregating PR
> Add all properties to the BlueBlockUser interface

- src/constants.ts
- src/content/index.ts
- src/global.d.ts
- src/parsers/instructions.ts
- src/parsers/search.ts
- src/parsers/timeline.ts
- src/popup/index.ts
- src/shared.ts
this is what I meant by compiling the config
I didn't test this
> compile config

- src/global.d.ts
- src/shared.ts
- src/utilities.ts
fixes https://github.com/kheina-com/Blue-Blocker/issues/232
> use exponential backoff when messaging background script

- privacy.md
Yippie I get to use my rules lawyering brain for good instead of scaring my friends :))))
> Add privacy policy within repo

- package-lock.json
- package.json
- src/content/index.ts
- src/injected/inject.ts
- src/manifest.ts
- src/parsers/instructions.ts
Gets users from the retweets page of a tweet. Pretty quick and easy.
Closes #319.
To do:
1. - [x] test
- - [x] chrome
- - [ ] firefox 
2. - [x] squash & merge
3. - [ ] release
> Get users from the retweets page

- package-lock.json
- package.json
- src/manifest.ts
- vite-plugins.ts
Closes #323
Tested, good to go. I don't think this needs a new release since html-minifier is only used as a build step.
> Switch to html-minifier-terser

- privacy.md
Responding to #321. 
Maybe they'll be happy if we say that we don't send anything over the network?? Idk. I think the next step would be to add a consent popup just for firefox lol...
> Add a description of how data is processed to the privacy policy

- src/popup/style.css
Popped out to me in the logs from #327 lol
> Fix a small CSS syntax error

- readme.md
> Document `jq` dependency in readme.md

- package-lock.json
- package.json
- src/content/index.ts
- src/injected/inject.ts
- src/manifest.ts
- src/parsers/user.ts
Adds a new parser for the `GetUserByScreenName` endpoint. Pretty basic.
Closes #140.
> Add scraping of UserByScreenName API endpoint

- src/background/index.ts
- src/content/index.ts
- src/pages/history/index.ts
- src/pages/integrations/index.ts
- src/pages/queue/index.ts
- src/pages/safelist/index.ts
- src/parsers/instructions.ts
- src/popup/index.html
- src/popup/index.ts
- src/shared.ts
- src/utilities.ts
Migrates Soupcan to the new integration system. Closes #300.
I don't use Soupcan so I can't test this, I think it's right but someone should test it :)
> Soupcan migration

- package-lock.json
- package.json
- src/content/index.ts
- src/global.d.ts
- src/injected/inject.ts
- src/manifest.ts
- src/parsers/user.ts
Adds checking the users that get recommended in the sidebar, closes #164.
So far everything works in my testing! :)
> Add intercepting sidebar recommendations

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
maybe this will help people write better issues?
> [chore] add issue templates

- .github/CODEOWNERS
Need to be able to approve changes to the makefile lol
> Add @rougetimelord to makefile codeowner

- .github/workflows/release.yml
- makefile
Just a minor commentary addition to address the issue I experienced in testing #295
> Update makefile to add a comment about usage

- .github/CODEOWNERS
> add @rougetimelord to TS config files

- .github/workflows/release.yml
Simply bumping the Firefox release action version
> Update firefox release action

- .github/workflows/ci-main.yml
- .github/workflows/release.yml
I think this will fix the newest weird workflow quirk?? Maybe? Inshallah it will not crash this time?
> Remove equivalent paths from zip command, exclude editor config, add source zipping to 

- .github/workflows/release.yml
Ain't much to it... Should also let us (me) verify if the zip was done correctly lol :P
> [meta] add uploading the output zips to releases

- .github/release.yaml
Pretty meta, mostly just want to have prettier release notes for Mozilla to look at :P
> [meta] Add categories to the auto generated release notes

- package-lock.json
- package.json
- src/background/index.ts
- src/constants.ts
- src/content/index.ts
- src/content/startup.ts
- src/injected/inject.ts
- src/manifest.ts
- src/pages/consent/index.html
- src/pages/consent/index.ts
- src/pages/consent/style.css
- vite.config.ts
Fine, have your consent popup! Does that make you happy?
Probably should beautify the page a bit, but honestly, if having an ugly page is what it takes to get a working extension out to users I can live with it.
Thanks for all of the memories AMO team <3 Really feeling great about continuing to support your browser <3
> Add a consent popup for Firefox

- .github/workflows/prettier.yml
Oopsie I forgot about branch protection,  hopefully just smuggling in prettier changes works?
> Use same commit for prettier
